// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxhJIUdY9O1gaAbBYXj76qmWO7E8n8yA4',
    appId: '1:46866811170:web:1cb798917b5a9f0703bd7b',
    messagingSenderId: '46866811170',
    projectId: 'flutter-todo-app-50d70',
    authDomain: 'flutter-todo-app-50d70.firebaseapp.com',
    storageBucket: 'flutter-todo-app-50d70.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIR9ioadv5ykDFl2bzYOsfcKLDqqYMRSg',
    appId: '1:46866811170:android:b7524a1e891c665203bd7b',
    messagingSenderId: '46866811170',
    projectId: 'flutter-todo-app-50d70',
    storageBucket: 'flutter-todo-app-50d70.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxGkNfgf6Eqh0CNUeht9PV1xj5-DD2mWQ',
    appId: '1:46866811170:ios:a1dcbc3aa87daaf103bd7b',
    messagingSenderId: '46866811170',
    projectId: 'flutter-todo-app-50d70',
    storageBucket: 'flutter-todo-app-50d70.firebasestorage.app',
    iosBundleId: 'com.example.flutterTodoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxGkNfgf6Eqh0CNUeht9PV1xj5-DD2mWQ',
    appId: '1:46866811170:ios:a1dcbc3aa87daaf103bd7b',
    messagingSenderId: '46866811170',
    projectId: 'flutter-todo-app-50d70',
    storageBucket: 'flutter-todo-app-50d70.firebasestorage.app',
    iosBundleId: 'com.example.flutterTodoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxhJIUdY9O1gaAbBYXj76qmWO7E8n8yA4',
    appId: '1:46866811170:web:23bd77b4c980e1c103bd7b',
    messagingSenderId: '46866811170',
    projectId: 'flutter-todo-app-50d70',
    authDomain: 'flutter-todo-app-50d70.firebaseapp.com',
    storageBucket: 'flutter-todo-app-50d70.firebasestorage.app',
  );

}